#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
TASK_TEMPLATE_ROOT = Path(
    os.environ.get(
        "LOOPSBENCH_CONTRIBUTION_TEMPLATE_ROOT",
        REPO_ROOT.parent / "tasks" / "_template",
    )
).resolve()
OUTPUT_PATH = Path(
    os.environ.get(
        "LOOPSBENCH_CONTRIBUTION_OUTPUT_PATH",
        REPO_ROOT / "src" / "data" / "generatedContribution.ts",
    )
).resolve()


def _tree_lines(root: Path) -> list[str]:
    def visible_children(path: Path) -> list[Path]:
        return sorted(
            [child for child in path.iterdir() if child.name != ".gitkeep"],
            key=lambda child: (not child.is_dir(), child.name),
        )

    lines = ["tasks/task_my_new_case/"]

    def walk(path: Path, prefix: str) -> None:
        children = visible_children(path)
        for index, child in enumerate(children):
            is_last = index == len(children) - 1
            connector = "`-- " if is_last else "|-- "
            label = f"{child.name}/" if child.is_dir() else child.name
            lines.append(f"{prefix}{connector}{label}")
            if child.is_dir():
                walk(child, f"{prefix}{'    ' if is_last else '|   '}")

    walk(root, "")
    return lines


def render_task_structure_example(root: Path) -> str:
    return "\n".join(_tree_lines(root.resolve()))


def main() -> None:
    if not TASK_TEMPLATE_ROOT.exists():
        raise SystemExit(f"Task template not found: {TASK_TEMPLATE_ROOT}")

    structure = render_task_structure_example(TASK_TEMPLATE_ROOT)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        "\n".join(
            [
                "/* This file is generated by scripts/generate_contribution_data.py. */",
                "",
                f"export const generatedTaskStructureExample = {structure!r};",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote contribution data to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
