/* This file is generated by scripts/generate_contribution_data.py. */

export const generatedTaskStructureExample = 'tasks/task_my_new_case/\n|-- base/\n|   `-- README.md\n|-- gold_patches/\n|   `-- example_unit.diff\n|-- requirements/\n|   `-- example_unit.yaml\n|-- tests/\n|   `-- test_outputs.py\n|-- Dockerfile\n|-- docker-compose.yaml\n|-- module_dag.yaml\n|-- run-tests.sh\n|-- slug_diff_map.json\n|-- solution.sh\n|-- task.yaml\n`-- unit_dag.json';
